### ISSUE TITLE
OOV are not replaced with UNK token when training and validation happens.

### ISSUE THREAD

**Issue by mpatsis** [michaelpradel/DeepBugs#5]
When using BugDetection.py unknown tokens are not converted into UNK and instances containing them are skipped.
For example, this happens in python/LearningDataSwappedArgs.py lines 65-69.
For that one this could be fixed by having python/Util.py replace OOV tokens in the call before yielding it.

I've checked this for the swapped arguments bugs but I guess that the same happens for the rest.
Please let me know if I have misunderstood how the above works.

**Comment by michaelpradel** [comment]
Your understanding is correct. We are skipping code snippets with unknown tokens because they don't provide a strong enough signal. Most bug patterns supported so far rely on only a few (e.g., two) identifiers/literals. If one of them is missing, the model doesn't have enough information for make a good decision. For other (new) bug patterns, this may be different and trying to replace unknown tokens with OOV may be worth a try.
